# Generated by Django 5.2.5 on 2025-08-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='password',
            field=models.CharField(default=12345678, max_length=255, verbose_name='Paroli'),
            preserve_default=False,
        ),
    ]
