# Generated by Django 5.2.5 on 2025-08-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_worker_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='category',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=20, verbose_name='Kategoriyasi'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
