# Generated by Django 5.2.5 on 2025-08-29 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_worker_category_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('students_count', models.PositiveIntegerField(default=0)),
                ('teacher', models.ForeignKey(limit_choices_to={'category': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='blog.worker')),
            ],
        ),
    ]
