# Generated by Django 5.2.5 on 2025-08-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='homeworks_submitted',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
